version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  unit-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/without-cache:
          steps:
            - run: npm install
            - run: npm run test
workflows:
  node-tests:
    jobs:
      - unit-test